//
//  Theme.swift
//  Pelt
//
//  Created by Brian Williams on 12/12/2017.
//  Copyright © 2017 Brian Williams. All rights reserved.
//

import Foundation
import Cocoa

class Theme {
    
    let majorVersion: Int = 5
    let minorVersion: String = "10.0_370"
    let schemaChangeCount: Int = 1
    let creator: String = "Pelt 1.0"
    let revision: String = "b8761d5b3a670e00b16e716b603a7c9f50dcfcb0" // NOTE: This needs to be changed
    
    var props: [String: Float] = [
        "MinVelocityNoteBlendFactor" : 0.200000003,
        "StripedBackgroundShadeFactor" : 0.8999999762,
        "AutomationLaneHeaderAlpha" : 60,
        "AutomationLaneClipBodyAlpha" : 60,
        "DefaultBlendFactor" : 0.8000000119,
        "IconBlendFactor" : 0.6499999762,
        "ClipBlendFactor" : 0.75,
        "NoteBorderStandbyBlendFactor" : 0.5,
        "RetroDisplayBlendFactor" : 0.8999999762,
        "CheckControlNotCheckedBlendFactor" : 0.5,
        "MixSurfaceAreaBlendFactor" : 0.349999994,
        "TextFrameSegmentBlendFactor" : 0.6000000238,
        "VelocityEditorForegroundSelectedBlendFactor" : 0.6000000238,
        "NoteDisabledSelectedBlendFactor" : 0.5
    ]
    
    var colors: [String : NSColor] = [
        "ControlForeground" : NSColor.gray,
        "TextDisabled" : NSColor.gray,
        "ControlDisabled" : NSColor.gray,
        "MeterBackground" : NSColor.gray,
        "SurfaceHighlight" : NSColor.gray,
        "SurfaceArea" : NSColor.gray,
        "Desktop" : NSColor.gray,
        "ViewCheckControlEnabledOn" : NSColor.gray,
        "ScrollbarInnerHandle" : NSColor.gray,
        "ScrollbarInnerTrack" : NSColor.gray,
        "ScrollbarOuterHandle" : NSColor.gray,
        "ScrollbarOuterTrack" : NSColor.gray,
        "ScrollbarLCDHandle" : NSColor.gray,
        "ScrollbarLCDTrack" : NSColor.gray,
        "DetailViewBackground" : NSColor.gray,
        "PreferencesTab" : NSColor.gray,
        "SelectionFrame" : NSColor.gray,
        "ControlBackground" : NSColor.gray,
        "ControlFillHandle" : NSColor.gray,
        "ChosenDefault" : NSColor.gray,
        "ChosenRecord" : NSColor.gray,
        "ChosenPreListen" : NSColor.gray,
        "ImplicitArm" : NSColor.gray,
        "RangeDefault" : NSColor.gray,
        "RangeDisabled" : NSColor.gray,
        "RangeDisabledOff" : NSColor.gray,
        "LearnMidi" : NSColor.gray,
        "LearnKey" : NSColor.gray,
        "LearnMacro" : NSColor.gray,
        "RangeEditField" : NSColor.gray,
        "RangeEditField2" : NSColor.gray,
        "BipolReset" : NSColor.gray,
        "ChosenAlternative" : NSColor.gray,
        "ChosenAlert" : NSColor.gray,
        "ChosenPlay" : NSColor.gray,
        "Clip1" : NSColor.gray,
        "Clip2" : NSColor.gray,
        "Clip3" : NSColor.gray,
        "Clip4" : NSColor.gray,
        "Clip5" : NSColor.gray,
        "Clip6" : NSColor.gray,
        "Clip7" : NSColor.gray,
        "Clip8" : NSColor.gray,
        "Clip9" : NSColor.gray,
        "Clip10" : NSColor.gray,
        "Clip11" : NSColor.gray,
        "Clip12" : NSColor.gray,
        "Clip13" : NSColor.gray,
        "Clip14" : NSColor.gray,
        "Clip15" : NSColor.gray,
        "Clip16" : NSColor.gray,
        "ClipText" : NSColor.gray,
        "ClipBorder" : NSColor.gray,
        "SelectionBackground" : NSColor.gray,
        "StandbySelectionBackground" : NSColor.gray,
        "SelectionForeground" : NSColor.gray,
        "StandbySelectionForeground" : NSColor.gray,
        "SurfaceBackground" : NSColor.gray,
        "AutomationColor" : NSColor.gray,
        "LoopColor" : NSColor.gray,
        "ArrangementRulerMarkings" : NSColor.gray,
        "DetailViewRulerMarkings" : NSColor.gray,
        "ShadowDark" : NSColor.gray,
        "ShadowLight" : NSColor.gray,
        "DisplayBackground" : NSColor.gray,
        "AbletonColor" : NSColor.gray,
        "WaveformColor" : NSColor.gray,
        "VelocityColor" : NSColor.gray,
        "Alert" : NSColor.gray,
        "ControlOnForeground" : NSColor.gray,
        "ControlOffForeground" : NSColor.gray,
        "ControlOnDisabledForeground" : NSColor.gray,
        "ControlOffDisabledForeground" : NSColor.gray,
        "ControlOnAlternativeForeground" : NSColor.gray,
        "ControlTextBack" : NSColor.gray,
        "ControlContrastFrame" : NSColor.gray,
        "ControlSelectionFrame" : NSColor.gray,
        "ControlContrastTransport" : NSColor.gray,
        "Progress" : NSColor.gray,
        "ProgressText" : NSColor.gray,
        "TransportProgress" : NSColor.gray,
        "ClipSlotButton" : NSColor.gray,
        "BrowserBar" : NSColor.gray,
        "BrowserBarOverlayHintTextColor" : NSColor.gray,
        "BrowserDisabledItem" : NSColor.gray,
        "BrowserSampleWaveform" : NSColor.gray,
        "AutomationDisabled" : NSColor.gray,
        "AutomationGrid" : NSColor.gray,
        "AutomationMouseOver" : NSColor.gray,
        "MidiNoteMaxVelocity" : NSColor.gray,
        "RetroDisplayBackground" : NSColor.gray,
        "RetroDisplayBackgroundLine" : NSColor.gray,
        "RetroDisplayForeground" : NSColor.gray,
        "RetroDisplayForeground2" : NSColor.gray,
        "RetroDisplayForegroundDisabled" : NSColor.gray,
        "RetroDisplayGreen" : NSColor.gray,
        "RetroDisplayRed" : NSColor.gray,
        "RetroDisplayHandle1" : NSColor.gray,
        "RetroDisplayHandle2" : NSColor.gray,
        "RetroDisplayScaleText" : NSColor.gray,
        "ThresholdLineColor" : NSColor.gray,
        "GainReductionLineColor" : NSColor.gray,
        "InputCurveColor" : NSColor.gray,
        "InputCurveOutlineColor" : NSColor.gray,
        "OutputCurveColor" : NSColor.gray,
        "OutputCurveOutlineColor" : NSColor.gray,
        "SpectrumDefaultColor" : NSColor.gray,
        "SpectrumAlternativeColor" : NSColor.gray,
        "Operator1" : NSColor.gray,
        "Operator2" : NSColor.gray,
        "Operator3" : NSColor.gray,
        "Operator4" : NSColor.gray,
        "DrumRackScroller1" : NSColor.gray,
        "DrumRackScroller2" : NSColor.gray,
        "FilledDrumRackPad" : NSColor.gray,
        "SurfaceAreaFocus" : NSColor.gray,
        "FreezeColor" : NSColor.gray,
        "GridLabel" : NSColor.gray,
        "ArrangerGridTiles" : NSColor.gray,
        "DetailGridTiles" : NSColor.gray,
        "TreeColumnHeadBackground" : NSColor.gray,
        "TreeColumnHeadForeground" : NSColor.gray,
        "TreeColumnHeadSelected" : NSColor.gray,
        "TreeColumnHeadFocus" : NSColor.gray,
        "TreeColumnHeadControl" : NSColor.gray,
        "TreeRowCategoryForeground" : NSColor.gray,
        "TreeRowCategoryBackground" : NSColor.gray,
        "SearchIndication" : NSColor.gray,
        "SearchIndicationStandby" : NSColor.gray,
        "KeyZoneBackground" : NSColor.gray,
        "KeyZoneCrossfadeRamp" : NSColor.gray,
        "VelocityZoneBackground" : NSColor.gray,
        "VelocityZoneCrossfadeRamp" : NSColor.gray,
        "SelectorZoneBackground" : NSColor.gray,
        "SelectorZoneCrossfadeRamp" : NSColor.gray,
        "ViewCheckControlEnabledOff" : NSColor.gray,
        "ViewCheckControlDisabledOn" : NSColor.gray,
        "ViewCheckControlDisabledOff" : NSColor.gray,
        "BackgroundClip" : NSColor.gray,
        "BackgroundClipFrame" : NSColor.gray,
        "WarperTimeBarRulerBackground" : NSColor.gray,
        "WarperTimeBarMarkerBackground" : NSColor.gray,
        "BipolarPotiTriangle" : NSColor.gray,
        "Poti" : NSColor.gray,
        "DeactivatedPoti" : NSColor.gray,
        "PotiNeedle" : NSColor.gray,
        "DeactivatedPotiNeedle" : NSColor.gray,
        "TransportOffBackground" : NSColor.gray,
        "TransportOffDisabledForeground" : NSColor.gray,
        "TransportSelectionBackground" : NSColor.gray
    ]
    
    weak var delegate: DataModelDelegate?
    
    func requestData(){
        let data: [String : NSColor] = [String : NSColor]()

        if let d = delegate {
            d.didRecieveDataUpdate(data: data)
        }
    }
}
